-- Seed FAQ items for homepage
INSERT INTO public.faq_items (page_path, question, answer, display_order, is_active) VALUES
('/', 'How do you help real estate developers with lead generation?', 'We provide comprehensive lead generation solutions including automated marketing funnels, CRM integration, landing page optimization, and multi-channel campaigns specifically designed for real estate developers and projects.', 1, true),
('/', 'What makes your e-commerce optimization different?', 'We combine advanced technology with deep e-commerce expertise. Our approach includes product discovery optimization, catalog SEO, performance marketing, and data enrichment that goes beyond basic consulting to deliver measurable results.', 2, true),
('/', 'Do you work with both real estate and e-commerce clients?', 'Yes, we''re uniquely positioned as a digital growth partner serving both verticals. Our real estate division focuses on lead generation and CRM automation, while our e-commerce division specializes in product discovery and performance marketing.', 3, true),
('/', 'How quickly can we see results from your services?', 'Most clients see initial improvements within 2-4 weeks of implementation. Significant conversion rate improvements typically occur within 6-8 weeks as the optimization strategies take full effect and data collection provides insights for further refinement.', 4, true),
('/', 'What platforms and technologies do you work with?', 'For real estate: CRM platforms, marketing automation tools, lead management systems. For e-commerce: Shopify Plus, Magento, WooCommerce, BigCommerce, Elasticsearch, Coveo, and custom solutions. Our strategies are platform-agnostic and focus on results.', 5, true);

-- Seed FAQ items for /faq page
INSERT INTO public.faq_items (page_path, question, answer, display_order, is_active) VALUES
('/faq', 'How do you help real estate developers with lead generation?', 'We provide comprehensive lead generation solutions including automated marketing funnels, CRM integration, landing page optimization, and multi-channel campaigns specifically designed for real estate developers and projects.', 1, true),
('/faq', 'What makes your e-commerce optimization different?', 'We combine advanced technology with deep e-commerce expertise. Our approach includes product discovery optimization, catalog SEO, performance marketing, and data enrichment that goes beyond basic consulting to deliver measurable results.', 2, true),
('/faq', 'Do you work with both real estate and e-commerce clients?', 'Yes, we''re uniquely positioned as a digital growth partner serving both verticals. Our real estate division focuses on lead generation and CRM automation, while our e-commerce division specializes in product discovery and performance marketing.', 3, true),
('/faq', 'How quickly can we see results from your services?', 'Most clients see initial improvements within 2-4 weeks of implementation. Significant conversion rate improvements typically occur within 6-8 weeks as the optimization strategies take full effect and data collection provides insights for further refinement.', 4, true),
('/faq', 'What platforms and technologies do you work with?', 'For real estate: CRM platforms, marketing automation tools, lead management systems. For e-commerce: Shopify Plus, Magento, WooCommerce, BigCommerce, Elasticsearch, Coveo, and custom solutions. Our strategies are platform-agnostic and focus on results.', 5, true);

-- Seed services
INSERT INTO public.services (slug, title, description, icon_name, link, gradient_from, gradient_to, border_color, display_order, is_active) VALUES
('seo-content-strategy', 'SEO & Content Strategy', 'Drive organic traffic with strategic SEO and compelling content that converts visitors into customers.', 'Search', '/services/seo', 'blue-500', 'blue-600', 'border-blue-200 hover:border-blue-400', 1, true),
('performance-marketing', 'Performance Marketing', 'Data-driven SEM campaigns that maximize ROI and drive qualified leads to your business.', 'Target', '/services/sem', 'purple-500', 'purple-600', 'border-purple-200 hover:border-purple-400', 2, true),
('ecommerce-optimization', 'E-commerce Optimization', 'Boost online sales with product discovery optimization and conversion rate improvements.', 'ShoppingCart', '/ecommerce', 'green-500', 'green-600', 'border-green-200 hover:border-green-400', 3, true),
('real-estate-lead-gen', 'Real Estate Lead Gen', 'Automated lead generation and CRM solutions specifically designed for real estate developers.', 'Building2', '/real-estate', 'orange-500', 'orange-600', 'border-orange-200 hover:border-orange-400', 4, true),
('conversion-optimization', 'Conversion Optimization', 'Increase your conversion rates with A/B testing, UX improvements, and data-driven optimizations.', 'TrendingUp', '/services/conversion-optimization', 'indigo-500', 'indigo-600', 'border-indigo-200 hover:border-indigo-400', 5, true),
('performance-analytics', 'Performance Analytics', 'Comprehensive analytics and reporting to track performance and make data-driven decisions.', 'BarChart3', '/services/data-enrichment', 'teal-500', 'teal-600', 'border-teal-200 hover:border-teal-400', 6, true);

-- Seed blog posts
INSERT INTO public.blog_posts (slug, title, excerpt, content, author, category, image_url, published_at, is_published) VALUES
('seo-ecommerce-guide', 'Complete SEO Guide for E-commerce Websites', 'Learn proven strategies to boost your online store''s search rankings and drive organic traffic.', '<h2>Why SEO Matters for E-commerce</h2><p>Search Engine Optimization (SEO) is the cornerstone of successful e-commerce marketing. Unlike paid advertising, organic search traffic provides sustainable, long-term growth for your online store.</p><h2>Essential On-Page SEO Elements</h2><p>Successful e-commerce SEO starts with strong on-page optimization. Every product page, category page, and piece of content should be strategically optimized.</p><h3>Product Page Optimization</h3><ul><li><strong>Title Tags:</strong> Include primary keywords and product details</li><li><strong>Meta Descriptions:</strong> Write compelling descriptions that encourage clicks</li><li><strong>Product Descriptions:</strong> Create unique, detailed descriptions</li></ul>', 'Jane Smith', 'SEO', 'https://images.unsplash.com/photo-1562577309-4932fdd64cd1?w=800&h=400&fit=crop', '2024-01-15', true),
('product-discovery-optimization', 'Optimizing Product Discovery: Advanced Search and Navigation', 'Enhance your e-commerce site''s search functionality and navigation to help customers find products faster.', '<h2>The Importance of Product Discovery</h2><p>Product discovery is the process by which customers find and evaluate products on your e-commerce site. Effective product discovery can dramatically increase conversion rates.</p><h2>Search Functionality Best Practices</h2><p>Your site''s search function is often the fastest path between customer intent and product discovery.</p>', 'Michael Chen', 'Product Discovery', 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=400&fit=crop', '2024-01-10', true),
('marketpulse-analytics', 'MarketPulse Analytics: Understanding Your Competitive Landscape', 'Leverage data analytics to gain competitive insights and make informed business decisions.', '<h2>Introduction to Competitive Intelligence</h2><p>In today''s rapidly evolving e-commerce landscape, understanding your competitive position is crucial for sustainable growth.</p><h2>Key Metrics for Market Analysis</h2><p>Effective market pulse analysis relies on tracking the right metrics.</p>', 'John Davis', 'Data Enrichment', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=400&fit=crop', '2024-01-08', true),
('performance-marketing-strategies', 'Performance Marketing Strategies for Maximum ROI', 'Data-driven approaches to optimize your marketing spend and achieve better returns on investment.', '<h2>Understanding Performance Marketing</h2><p>Performance marketing is a results-driven approach to digital advertising where you only pay when specific actions are completed.</p><h2>Key Performance Marketing Channels</h2><p>Success in performance marketing requires understanding and leveraging the right channels for your business goals.</p>', 'Sarah Johnson', 'SEM', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=400&fit=crop', '2024-01-05', true),
('conversion-optimization-techniques', 'Advanced Conversion Rate Optimization Techniques', 'Proven methods to increase your website''s conversion rate and maximize revenue from existing traffic.', '<h2>The Foundation of Conversion Optimization</h2><p>Conversion Rate Optimization (CRO) is the systematic process of increasing the percentage of website visitors who complete desired actions.</p><h2>User Experience Fundamentals</h2><p>Every aspect of your website''s user experience impacts conversion rates.</p>', 'Emily Roberts', 'Conversion Optimization', 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&h=400&fit=crop', '2024-01-02', true),
('real-estate-lead-generation', 'Lead Generation Strategies for Real Estate Developers', 'Effective tactics to generate high-quality leads for real estate projects and developments.', '<h2>The Real Estate Lead Generation Landscape</h2><p>Real estate development projects require sophisticated lead generation strategies to attract qualified buyers and investors.</p><h2>Multi-Channel Marketing Approach</h2><p>Success in real estate lead generation comes from coordinating efforts across multiple marketing channels.</p>', 'David Wilson', 'Lead Generation', 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=400&fit=crop', '2023-12-28', true);