// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eorcqkxfqhgzmbobigcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvcmNxa3hmcWhnem1ib2JpZ2NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MTgxMjksImV4cCI6MjA2NTE5NDEyOX0.g8flaE0oox8YB_QFcyxKyz3_Xsx7CvB3CqEBQc-wuto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);